### ISSUE TITLE
LOGO/ICON PROPOSAL FOR HomeAssist-Android-App

### ISSUE THREAD

**Issue by orlant** [ascillato/HomeAssist-Android-App#2]
It is a pleasure to say hello to Mr. Ascillato, as he has realized, I enjoy making contributions to projects. I have seen that your application is missing an icon that represents it. If you allow me, I can create a minimalist logo / icon to upload and use in your repository.

**Comment by ascillato** [comment]
Hi,

This is a fork.

You should post that in the original branch

Thanks
